name: flappy
channels:
  - defaults
dependencies:
  - python=3.10.0
  - pip
  - pip:
    - flappy-bird-gymnasium
    - gymnasium
    - numpy
    - pygame
    - jupyter
    - tensorflow
    - torch
    - opencv-python
    - tqdm